name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Log in to Nexus
        uses: docker/login-action@v1
        with:
          registry: docker.magicmemories.com
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Format Check
        run: make fmtcheck
      -
        name: Vet
        run: make vet
      -
        name: Run acceptance tests
        run: make testacc